# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('identifier', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending_sender_confirmation', 'pending_sender_confirmation'), ('sent', 'sent'), ('read', 'read')], default='pending_sender_confirmation', max_length=255)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_email_token', models.CharField(db_index=True, max_length=255)),
                ('sender_ip', models.GenericIPAddressField()),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_email_token', models.CharField(db_index=True, max_length=255)),
                ('message', models.TextField()),
                ('sender_named', models.BooleanField(default=False)),
                ('sender_approved_public', models.BooleanField(default=False)),
                ('sender_approved_public_named', models.BooleanField(default=False)),
                ('recipient_approved_public', models.BooleanField(default=False)),
                ('recipient_approved_public_named', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
