# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_blacklistedemail_stripped_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient_email_stripped',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender_email_stripped',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
