# Generated by Django 2.0 on 2019-04-16 12:37
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_auto_20160423_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
