# Generated by Django 2.0 on 2019-05-08 11:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_message_recipient_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]